### ISSUE TITLE
Table of Contents formatting broken

### ISSUE THREAD

**Issue by SD10** [SwifterSwift/SwifterSwiftDocs#15]
![screen shot 2017-03-22 at 3 36 49 pm](https://cloud.githubusercontent.com/assets/7445580/24219599/6500b870-0f15-11e7-90c0-60745fdb6550.png)

Hey guys, sorry I had a crazy few weeks but am back to help! I noticed the table of contents for the extension md files are a little messed up. Any idea what the problem is?

**Comment by omaralbeik** [comment]
Looks like Github changed something in their markdown parser,
I updated all files in #16

**Comment by SD10** [comment]
Thank you @omaralbeik!
